/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SongOrAlbumNFT } from "./SongOrAlbumNFT";

export { SongOrAlbumNFT__factory } from "./factories/SongOrAlbumNFT__factory";
